### ISSUE TITLE
Direkdemokraterna saknas...

### ISSUE THREAD

**Issue by dpriskorn** [Ackuq/partiguiden#1252]
se https://nya.direktdemokraterna.se/
De kör CONSUL här https://consul.direktdemokraterna.se/ se https://consulproject.org/en/ vilket är ett fritt program som möjliggör att medborgare tillsammans tar fram politik.
CONSUL används på många håll för arbete mot FNs SDG enligt hemsidan. 

Direktdemokrati kortslutar lite den partipolitiska processen där vi förväntas lita blindt på vallöften från partimedlemmar och rösta en gång var fjärde år för sedan att vara helt utelämnade utan möjlighet att dra tillbaka mandatet om de inte gör som de sa innan valet.
I en direktdemokrati har man ledamöter i riksdagen som bara röstar enligt vad medlemmarna röstat fram i CONSUL tex. Ledamöterna är således folkets röst mellan valen.

**Comment by Ackuq** [comment]
Hej! Vi har valt att enbart fokusera på partier som är medlemmar i riksdagen. Detta är för att lätt ha en opartisk och tydlig avgränsning för vilka partier ska vara inkluderade och inte. 😄
