### ISSUE TITLE
Länkröta exempel KD

### ISSUE THREAD

**Issue by salgo60** [Ackuq/partiguiden#1306]
**KD dokumentet https://kristdemokraterna.se/var-politik/politik-a-o refereras i API:et 278 ggr och har tagits bort av KD**

[aHR0cHM6Ly9rcmlzdGRlbW9rcmF0ZXJuYS5zZS92YXItcG9saXRpay9wb2xpdGlrLWEtby8jQWJvcnQ=](https://backend.partiguiden.se/standpoints/?format=api)

```
{
        "id": "aHR0cHM6Ly9rcmlzdGRlbW9rcmF0ZXJuYS5zZS92YXItcG9saXRpay9wb2xpdGlrLWEtby8jQWJvcnQ=",
        "title": "Abort ",
        "content": [
            "Kristdemokraterna står bakom den svenska abortlagstiftningen där kvinnan själv har rätt att besluta om hon vill göra abort till och med graviditetsvecka 18, och att det därefter är Socialstyrelsens rättsliga råd som beslutar om tillstånd för abort. Kristdemokraterna menar att samhället ska arbeta förebyggande och ge stöd för att minska antalet oönskade graviditeter och aborter. Både kvinnan och fostret är skyddsvärda individer. Bästa möjliga hjälp ska erbjudas så att inte praktiska, ekonomiska eller sociala svårigheter hindrar en kvinna att fullfölja sin graviditet. Vi vill också att kommuner och regioner ska satsa mer på stödjande och förebyggande verksamhet, såsom ungdomsmottagningar, subventionerade preventivmedel och elevhälsa."
        ],
        "date": "2022-06-26",
        "link": "https://kristdemokraterna.se/var-politik/politik-a-o/#Abort",
        "party": "KD",
        "subject": 2
    },
 ```
 
 * https://kristdemokraterna.se/var-politik/politik-a-o/
* finns på https://web.archive.org/web/20220701041407/https://kristdemokraterna.se/var-politik/politik-a-o/
   *  räcker med https://web.archive.org/web/https://kristdemokraterna.se/var-politik/politik-a-o/
   * sidan har **hämtats 22 ggr av IA** se https://web.archive.org/web/20220000000000*/https://kristdemokraterna.se/var-politik/politik-a-o/
   * alla sidor i IA från [https://kristdemokraterna.se*](https://web.archive.org/web/*/https://kristdemokraterna.se*)   
   
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/14206509/181603608-d16fa310-b39a-4a52-9d8f-4616ffbd096f.png">

**Comment by salgo60** [comment]
[Tweet](https://twitter.com/salgo60/status/1552711727304908801)

<img width="849" alt="image" src="https://user-images.githubusercontent.com/14206509/181603361-d1c9cd48-96df-4069-b44a-fbabe669aa6b.png">

**Comment by Ackuq** [comment]
Får se till att fixa integrationen med web archive.. Ska se till att uppdatera så att datan kan hämtas rätt som en quick fix. 

Tack så mycket som upplyser mig om detta! Samt att du tar upp det med KD. Har så lite tid och energi efter jobbet så mycket sånt här flyger under min radar 😓

**Comment by salgo60** [comment]
Tycker det du gjort är magiskt snyggt men partierna borde "styras upp" så att dom besvarar vissa frågor och det kopplas till strukturerat data....

* tveksam om det går känns inte som det är IT A-laget som håller på med politik även att skillnaderna blir bara stärre med A och B-laget....

Updatering SDG vi fick idag en ny version av API-et så jag körde om min [Notebook](https://github.com/salgo60/SDGMapperSweden/blob/main/Notebook/partiguiden%20SDG.ipynb) blev fler träffar.... bäst vore det även här var om partierna kunde peka på vad dom 
* vill göra per hållbarhetsmålen
* vilka motioner dom lagt i Riksdagen per hållbarhetsmål etc...

**Comment by salgo60** [comment]
Ingen feedback KD
